services:
    - type: web
      name: flyer-agent
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
      envVars:
          - key: MISTRAL_API_KEY
            sync: false
          - key: SENDER_EMAIL
            sync: false
          - key: SENDER_PASSWORD
            sync: false
